### ISSUE TITLE
Triplet Loss Error

### ISSUE THREAD

**Issue by Zasder3** [GerardLiu96/FECNet#1]
You have a nice implementation however I believe there is an error in your loss metric. You calculate a normal triplet loss instead of that implemented in the paper. They utilized a "double" triplet so to speak:
![image](https://user-images.githubusercontent.com/5066934/62218448-187d0180-b372-11e9-907f-3418acd35145.png)
You just need a second distance and to add the other triplet.

All the Best,
Cade

**Comment by GerardLiu96** [comment]
Thank you for your comment! I fixed this problem now!

All the Best,
Gerard

**Comment by GerardLiu96** [comment]
> You have a nice implementation however I believe there is an error in your loss metric. You calculate a normal triplet loss instead of that implemented in the paper. They utilized a "double" triplet so to speak:
> ![image](https://user-images.githubusercontent.com/5066934/62218448-187d0180-b372-11e9-907f-3418acd35145.png)
> You just need a second distance and to add the other triplet.
> 
> All the Best,
> Cade

Thank you for your comment! I fixed this problem now!

All the Best,
Gerard
