### ISSUE TITLE
triplet_loss&train

### ISSUE THREAD

**Issue by hfutfl** [GerardLiu96/FECNet#2]
I have changed your code 'd = K.sum(d1, d2)' in triplet_loss to 'd = tf.add(d1, d2)', and  i use keras 2.2.4 ,tensorflow 1.9.0 to train the model ,I have the same gpu like you,but the train process is so fast within in one minutes that I can't belive it ? Is there anything wrong?

**Comment by GerardLiu96** [comment]
> tf.add

Basiclly, yes. But the model performance is bad in my experiment, and the google research team reply me that maybe because I could only have a small batch size due to the device limitation. Or maybe there are some other bugs in my codes.
