### ISSUE TITLE
image-extract

### ISSUE THREAD

**Issue by hfutfl** [GerardLiu96/FECNet#3]
when I run the image-extract.py ,the pycharm shows 'FileNotFoundError: [Errno 2] No such file or directory: 'data/train/11841407964_65d840b4a5_b.jpg' ',I'm in China,is  the  net's  problem?

**Comment by GerardLiu96** [comment]
> when I run the image-extract.py ,the pycharm shows 'FileNotFoundError: [Errno 2] No such file or directory: 'data/train/11841407964_65d840b4a5_b.jpg' ',I'm in China,is the net's problem?

You need to create the directory data/train/ and data/test/ by your self first, and then, if it still don't work, then it's possiblely the network issue.
