### ISSUE TITLE
About data loader bug

### ISSUE THREAD

**Issue by llpspark** [GerardLiu96/FECNet#4]
Hi, Think u for this implement for FECnet paper, I have reimplement this paper with Pytorch and reference some idea from u.  I found some error in your data acquirement part, e,g. different triplet images has different patch location althrough in same orignal image.  Detaily, u can see: https://github.com/llpspark/FECNet_for_FER/blob/master/datas/download_image.py and https://github.com/llpspark/FECNet_for_FER/blob/master/datas/fec_data.py

**Comment by GerardLiu96** [comment]
> Hi, Think u for this implement for FECnet paper, I have reimplement this paper with Pytorch and reference some idea from u. I found some error in your data acquirement part, e,g. different triplet images has different patch location althrough in same orignal image. Detaily, u can see: https://github.com/llpspark/FECNet_for_FER/blob/master/datas/download_image.py and https://github.com/llpspark/FECNet_for_FER/blob/master/datas/fec_data.py

Thank you, but I don't think it will cause any problem except using more space in your computer.
