### ISSUE TITLE
FECWithPretrained.py

### ISSUE THREAD

**Issue by hfutfl** [GerardLiu96/FECNet#5]
excuse me,when i try to train the FECWithPretrained.py with  the fuction  generate_arrays_from_file, it tell me "ValueError: cannot reshape array of size 48 into shape (48,224,224,3)",how can i fix it?

**Comment by GerardLiu96** [comment]
> excuse me,when i try to train the FECWithPretrained.py with the fuction generate_arrays_from_file, it tell me "ValueError: cannot reshape array of size 48 into shape (48,224,224,3)",how can i fix it?

You does not correctly read the data
